mikrotik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('inventories/', include('inventories.urls')),
    path('nodos/', include('nodos.urls')),
    path('routers/', include('routers.urls')),
    path('users/', include('users.urls')),
    path('administration/', include('administration.urls')),
    path('alerts/', include('alerts.urls')),
    path('ventas/', include('ventas.urls')),
    path('supports/', include('supports.urls')),
    path('text_messages/', include('text_messages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nodos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='nodos.index'),
    path('show/<int:id>/', views.show, name='nodos.show'),
    path('show/antenna/<str:ip>', views.antenna, name='nodos.show.antenna'),
]

routers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='routers.index'),
    path('show/<int:id>/', views.show, name='routers.show'),
    path('queue/add/<int:id>/', views.addQueue, name='routers.queue.add'),
    path('ppp/add/<int:id>/', views.addPpp, name='routers.ppp.add'),
    path('address/add/<int:id>', views.addAddress, name='routers.address.add'),
    path('plans/', views.plans, name='routers.plans.index'),
]

routers/models.py
from django.db import models
from fernet_fields import EncryptedTextField

from nodos.models import Nodo

class Olt(models.Model):
    name = models.CharField(max_length=30)
    user = models.CharField(max_length=20)
    password = EncryptedTextField()
    ip = models.GenericIPAddressField(protocol='both', unpack_ipv4=False)
    
    def __str__(self):
        return self.name
    
class Router(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre del Router')
    ip = models.GenericIPAddressField(protocol='both', unpack_ipv4=False)
    user = models.CharField(max_length=100, verbose_name='Usuario')
    password = EncryptedTextField()
    port = models.IntegerField(default=8728)
    sms = models.BooleanField(default=False, verbose_name='Mensajes SMS.')
    ssh_port = models.IntegerField(default=None, null=True, blank=True)
    nodo = models.ForeignKey(Nodo, blank=True, null=True, on_delete=models.RESTRICT)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        
class Plan(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre del Plan')
    code = models.CharField(max_length=30, verbose_name='Codigo')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Precio')
    routers = models.ManyToManyField(Router)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

routers/forms.py
from django.forms import ModelForm
from .models import Router
from django import forms

class RouterForm(ModelForm):
    class Meta:
        model = Router
        exclude = ('created_at',)
        widgets = {
            'password': forms.PasswordInput(),
        }

class QueueForm(forms.Form):
    name = forms.CharField(label='Name')
    target = forms.GenericIPAddressField(label='IP')
    destination = forms.GenericIPAddressField(label='dst', required=False)
    upload = forms.CharField(label='Upload')
    download = forms.CharField(label='Download')

class PppForm(forms.Form):
    name = forms.CharField(label='Name')
    password = forms.CharField(label='Password', required=False)
    comment = forms.CharField(label='comment', required=False)
    profile = forms.ChoiceField(label='profiles', widget=forms.Select)

class AddressFrom(forms.Form):
    address = forms.GenericIPAddressField(label='Address')
    network = forms.GenericIPAddressField(label='Network', required=False)
    interface = forms.ChoiceField(label='Interface', widget=forms.Select)

routers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.http import HttpResponseRedirect
from clients.models import Profile
from .models import Router, Plan
from .forms import RouterForm, QueueForm, PppForm, AddressFrom

import routeros_api, folium

### ESTABLECEMOS CONEXION CON EL ROUTER

class Connection:
    
    def __init__(self, router):
        self.active = False
        try:
            self.connection = routeros_api.RouterOsApiPool(
                router.ip,
                username=router.user,
                password=router.password,
                port=router.port,
                plaintext_login=True,
            )
            self.api = self.connection.get_api()
            self.active = True

        except ObjectDoesNotExist:
            self.message = 'ROUTER NO REGISTRADO'
        except routeros_api.exceptions.RouterOsApiCommunicationError:
            self.message = 'USUARIO O CLAVE INCORRECTOS'
        except routeros_api.exceptions.RouterOsApiConnectionError:
            self.message = 'NO PUDO CONECTAR CON EL ROUTER'
    
    def query(self, query):
        _query = self.api.get_resource(query)
        get_query = _query.get()
        return get_query
    
    def name_query(self, query, name):
        _query = self.api.get_resource(query).get(name=name)
        return _query

    def disconnect(self):
        self.connection.disconnect()


def router_connection(request, id):
    try:
        router = Router.objects.get(id=id)
        connection = routeros_api.RouterOsApiPool(
            router.ip,
            username=router.user,
            password=router.password,
            port=router.port,
            plaintext_login=True,
        )
        api = connection.get_api()
        return connection, api, router
    except ObjectDoesNotExist:
        messages.error(request, 'ROUTER NO REGISTRADO')
    except routeros_api.exceptions.RouterOsApiCommunicationError:
        messages.error(request, 'USUARIO O CLAVE INCORRECTOS')
    except routeros_api.exceptions.RouterOsApiConnectionError:
        messages.error(request, 'NO PUDO CONECTAR CON EL ROUTER')
    return redirect(request.META.get('HTTP_REFERER')), 0, 0

def router_disconnection(connection):
    # TERMINAR CONEXION
    connection.disconnect()

def index(request):
    routers = Router.objects.all()
    return render(request, 'routers/index.html', {'routers': routers})

def show(request, id):
    # ORDENAR
    """
    - EL PRIMER PARAMETRO ES LA LISTA O DICCIONARIO A ORDENAR.
    - EL SEGUNDO PARAMETRO ES LA CLAVE POR LA QUE VA A ORDENAR
    """
    def order(list_, key_):
        newlist = sorted(list_, key=lambda d: d[key_])
        return newlist

    connection, api, router = router_connection(request, id)
    if isinstance(connection, HttpResponseRedirect):
        return connection

    #identity
    identity_query = api.get_resource('/system/identity')
    identity = identity_query.get()

    #routerboard
    resource_query = api.get_resource('/system/resource')
    resource = resource_query.get()

    #health
    health_query = api.get_resource('/system/health')
    health = health_query.get()

    interfaces_query = api.get_resource('/interface/ethernet')
    interfaces = interfaces_query.get()

    ppp = api.get_resource('/ppp/secret')
    usuarios = order(ppp.get(), 'name')
    users_not_registered = []
    for user in usuarios:
        try:
            _user = Profile.objects.get(name=user['name'], router=id)
        except:
            if user['disabled'] == 'false':
                users_not_registered.append(user['name'])

    queues_query = api.get_resource('/queue/simple')
    queues = order(queues_query.get(), 'name')

    ips_query = api.get_resource('/ip/address')

    ips = order(ips_query.get(), 'address')

    if router.nodo:
        if router.nodo.coordinates:
            coordinates = router.nodo.coordinates
            x = coordinates.split(',')
            map = folium.Map(location=[float(x[0]), float(x[1])], zoom_start=16)
            folium.Marker([float(x[0]), float(x[1])], tooltip='Clip aqui').add_to(map)
            folium.TileLayer(
                tiles='https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
                attr='Google',
                name='Google Satellite',
                overlay=True,
                control=False
            ).add_to(map)

            map_render = map.get_root().render()
        else:
            map_render = None
    else:
        map_render = None

    context = {
        'router': router,
        'identity': identity,
        'interfaces': interfaces,
        'health': health,
        'resource': resource,
        'usuarios': usuarios,
        'users_not_registered': users_not_registered,
        'queues': queues,
        'ips': ips,
        'map': map_render
    }

    router_disconnection(connection)
    return render(request, 'routers/show.html', context)

def addQueue(request, id):
    connection, api, router = router_connection(request, id)
    if isinstance(connection, HttpResponseRedirect):
        return connection

    if request.method == 'POST':
        form = QueueForm(request.POST)
        if form.is_valid():


            # REGISTRAR QUEUE
            add_queue = api.get_resource('/queue/simple')
            add_queue.add(
                name = request.POST['name'],
                max_limit = request.POST['upload'] + '/' + request.POST['download'],
                target = request.POST['target']
            )

            # TERMINAR CONEXION
            router_disconnection(connection)

            messages.success(request, 'QUEUE REGISTRADO CON EXITO')
            return redirect('routers.show', router.id)
        else:
            messages.error(request, 'EL FORMULARIO NO ES VALIDO')
            return redirect(request.META.get('HTTP_REFERER'))

    form = QueueForm()
    context = {
        'form': form,
        'router': router
    }
    return render(request, 'routers/queue/add.html', context)

def addPpp(request, id):
    connection, api, router = router_connection(request, id)
    if isinstance(connection, HttpResponseRedirect):
        return connection

    if request.method == 'POST':
        # REGISTRANDO PPP
        add_ppp = api.get_resource('/ppp/secret')
        add_ppp.add(
            name=request.POST['name'],
            service='pppoe',
            password=request.POST['password'],
            profile=request.POST['profile'],
        )

        # TERMINAR CONEXION
        router_disconnection(connection)

        messages.success(request, 'PPP REGISTRADO CON EXITO')
        return redirect('routers.show', id)

    # GET PPP PROFILES
    profiles_ = api.get_resource('/ppp/profile')
    profiles = profiles_.get()

    # TERMINAR CONEXION
    router_disconnection(connection)
    list_ = []
    for item in profiles:
        list_.append((item['name'], item['name']))

    form = PppForm()
    form.fields['profile'].choices = list_

    context = {
        'form': form,
        'router': router
    }
    return render(request, 'routers/ppp/add.html', context)

def addAddress(request, id):
    connection, api, router = router_connection(request, id)
    if isinstance(connection, HttpResponseRedirect):
        return connection

    if request.method == 'POST':
        # REGISTRAR ADDRESS
        add_address = api.get_resource('/ip/address')
        add_address.add(
            address = request.POST['address'],
            network = request.POST['network'],
            interface = request.POST['interface']
        )

        messages.success(request, 'ADDRESS AGREGADO CON EXITO')
        return redirect('routers.show', id)

    # GET INTERFACES
    interfaces_ = api.get_resource('/interface')
    interfaces = interfaces_.get()
    form = AddressFrom()
    interfaces_list_ = []
    for item in interfaces:
        if item['type'] != 'pppoe-in':
            interfaces_list_.append((item['name'], item['name']))
    form.fields['interface'].choices = interfaces_list_
    context = {
        'form': form,
        'router': router
    }
    return render(request, 'routers/address/add.html', context)

def plans(request):
    plans = Plan.objects.all()
    context = {
        'plans': plans
    }
    return render(request, 'routers/plans/index.html', context)

templates/routers/index.html
{% extends "layouts/app.html" %}

{% block 'content' %}

    <div class="row">
        <div class="col s12">
            <h6>Routers</h6>
        </div>
    </div>
    <div class="divider"></div>
    <div class="row">
        <div class="col s12">
            {% if routers %}
                <table class="responsive-table">
                    <tbody>
                        {% for router in routers %}
                            <tr>
                                <td><a href="{% url 'routers.show' router.id %}">{{ router }}</a></td>
                                <td>Planes: {{ router.plan_set.all | length }}</td>
                                <td>Profiles: {{ router.profile_set.all | length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h6 class="center">NO HAY ROUTERS REGISTRADOS</h6>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/routers/show.html
{% extends 'layouts/app.html' %}


{% block 'head' %}
{% load static %}
<link rel="stylesheet" href="{% static 'routers/css/routersTable.css' %}">
{% endblock %}

{% block 'content' %}

    {% if router %}
    <div class="row">
        <h1>{{ router }}</h1>
        <div class="col m5">
            <p><b>NOMBRE DEL EQUIPO:</b> {{ identity.0.name | upper }}</p>
            <p><b>INTERFACES:</b> {{ interfaces | length }}</p>
            <p><b>UPTIME:</b> {{ resource.0.uptime }}</p>
            <p><b>VERSION:</b> {{ resource.0.version }}</p>
        </div>
        <div class="col m7">
            {% if map %}
                <div class="">
                    <iframe srcdoc="{{ map }}" frameborder="0" width="100%" height='200px'>
                    </iframe>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        {% if users_not_registered %}
            <div class="col s12">
                <ul class="collapsible">
                    <li>
                        <div class="collapsible-header">USUARIOS NO REGISTRADOS EN EL SISTEMA <span class="badge">{{ users_not_registered | length }}</span></div>
                        <div class="collapsible-body">
                            <br>
                            <table>
                                <thead>
                                    <tr>
                                        <th>USUARIO</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for user in users_not_registered %}
                                        <tr>
                                            <td>{{ user }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </li>
                </ul>
            </div>
        {% endif %}

        <div class="col s12">
            <ul class="collapsible">
                <li>
                    <div class="collapsible-header">QUEUES SIMPLES <span class="badge">{{ queues | length }}</span></div>
                    <div class="collapsible-body">
                        <div class="right-align">
                            <a href="{% url 'routers.queue.add' router.id %}" class="btn btn-small">Agregar queue</a>
                        </div>
                        <br>
                        <table>
                            <thead>
                                <tr>
                                    <th>NOMBRE</th>
                                    <th>TARGET</th>
                                    <th>PARENT</th>
                                    <th>QUEUE</th>
                                    <th>PRIORITY</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for queue in queues %}
                                    {% if queue.dynamic == 'false' %}
                                    <tr>
                                        <td>{{queue.name}}</td>
                                        <td>{{queue.target|truncatechars:18}}</td>
                                        <td>{{queue.parent}}</td>
                                        <td>{{queue.queue}}</td>
                                        <td>{{queue.priority}}</td>
                                    </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </li>
            </ul>
        </div>

        <div class="col s12">
            <ul class="collapsible">
                <li>
                    <div class="collapsible-header">PPP SECRET <span class="badge">{{ usuarios | length }}</span></div>
                    <div class="collapsible-body">
                        <div class="right-align">
                            <a href="{% url 'routers.ppp.add' router.id %}" class="btn btn-small">Agregar ppp</a>
                        </div>
                        <br>
                        <table>
                            <thead>
                                <tr>
                                    <th>NOMBRE</th>
                                    <th>PERFIL</th>
                                    <th>COMENTARIO</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in usuarios %}
                                    <tr>
                                        <td>{{user.name}}</td>
                                        <td>{{user.profile}}</td>
                                        <td>{{user.comment}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </li>
            </ul>
        </div>

        <div class="col s12">
            <ul class="collapsible">
                <li>
                    <div class="collapsible-header">IP ADDRESS <span class="badge">{{ ips | length }}</span></div>
                    <div class="collapsible-body">
                        <div class="right-align">
                            <a href="{% url 'routers.address.add' router.id %}" class="btn btn-small">Agregar ip</a>
                        </div>
                        <br>
                        <table>
                            <thead>
                                <tr>
                                    <th>ADDRESS</th>
                                    <th>NETWORK</th>
                                    <th>INTERFACE</th>
                                    <th>ENABLE</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ip in ips %}
                                    <tr>
                                        <td>{{ip.address}}</td>
                                        <td>{{ip.network}}</td>
                                        <td>{{ip.interface}}</td>
                                        {% if queue.disabled == 'true' %}
                                        <td class="red-text">Desabilitado</td>
                                        {% else %}
                                        <td class="green-text">Enable</td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    {% else %}
        <h5 class="center">{{ message }}</h5>
    {% endif %}

</div>
{% endblock %}

{% block 'javascript' %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.collapsible');
        var instances = M.Collapsible.init(elems, '');
    });
</script>
{% endblock %}